baseURL: https://comprar.to
languageCode: es-ES
title: comprar lo mejor
author: comprar.to
canonifyurls: true
paginate: 6
googleAnalytics: UA-6082386-11

params:
  brand: comprar.to
  description: Mira bien lo que compras. Compara los mejores productos de cada categoría.
  bgimg: img/alchemy.gif