baseURL = "https://compro.to"
languageCode = "es-ES"
title = "Compra lo mejor"
author = "compro.to"
canonifyurls = true
paginate = 3

[params]
brand = "compro.to"
description = "aether Hugo theme for blogs"
bgimg = "img/alchemy.gif"