baseURL: https://compro.to
languageCode: es-ES
title: Compra lo mejor
author: compro.to
canonifyurls: true
paginate: 3
googleAnalytics: UA-6082386-11

params:
  brand: compro.to
  description: Mira bien lo que compras. Compara los mejores productos de cada categoría.
  bgimg: img/alchemy.gif