baseURL: https://comprar.to
languageCode: es-ES
title: Comprar Todo Lo Que Me Gusta
author: comprar.to
canonifyurls: true
paginate: 6
googleAnalytics: UA-6082386-11
enableRobotsTXT: yes

permalinks:
  posts: /:title

outputs:
  page:
    - HTML
    - AMP

params:
  brand: comprar.to
  title: Comprar Todo Lo Que Me Gusta
  description: Mira bien lo que compras. Compara los mejores productos de cada categoría.
  bgimg: img/alchemy.gif